name: Run API tests on Docker

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit

      # Step 3: Clean up Docker Compose
      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose.yml down
